const CALENDARS={
 'fall-2026':{label:'Fall 2026',sessions:{full:['2026-08-24','2026-12-10'],first:['2026-08-24','2026-10-15'],second:['2026-10-26','2026-12-10']},closures:[['2026-09-25','2026-09-27'],['2026-10-01','2026-10-11']],swaps:{'2026-09-18':4}},
 'spring-2027':{label:'Spring 2027',sessions:{full:['2027-01-11','2027-05-07'],first:['2027-01-11','2027-03-04'],second:['2027-03-22','2027-05-07']},closures:[['2027-02-05','2027-02-14'],['2027-04-05','2027-04-05'],['2027-05-01','2027-05-03']],swaps:{'2027-04-06':1,'2027-04-07':2,'2027-04-08':3,'2027-04-09':4,'2027-05-04':1,'2027-05-05':2,'2027-05-06':3,'2027-05-07':4}}
};
const DAY_MAP={sun:0,sunday:0,su:0,mon:1,monday:1,m:1,tue:2,tues:2,tuesday:2,tu:2,wed:3,wednesday:3,w:3,thu:4,thur:4,thurs:4,thursday:4,th:4,fri:5,friday:5,f:5,sat:6,saturday:6,sa:6};
const DAY_NAMES=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'], COLORS=['#78c8ff','#ff82b7','#a8e85a','#ffd94d','#9d83ff'];
const SAMPLE=[
 {course:'COMPSCI 201',days:[1,3],start:'10:05',end:'11:20',location:'IB 2026',session:'full',notes:'Data Structures & Algorithms'},
 {course:'ECON 101',days:[2,4],start:'13:15',end:'14:30',location:'WDR 1001',session:'full',notes:'Economic Principles'},
 {course:'CHINESE 201',days:[1,2,4],start:'15:05',end:'15:55',location:'CC 305',session:'first',notes:'Intermediate Chinese'}
];
let courses=[],events=[];
const fileInput=document.querySelector('#schedule-file'),dropzone=document.querySelector('.dropzone'),toast=document.querySelector('#toast'),exportButton=document.querySelector('#export-button'),termSelect=document.querySelector('#term-select');

function say(message){toast.textContent=message;toast.classList.add('show');clearTimeout(say.timer);say.timer=setTimeout(()=>toast.classList.remove('show'),2400)}
function normalizeTime(value){const m=value.trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?$/i);if(!m)return'';let h=Number(m[1]);const min=Number(m[2]),ap=m[3]?.toUpperCase();if(min>59||h>(ap?12:23))return'';if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;return`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`}
function parseCsv(text){
 const rows=[];let row=[],cell='',quoted=false;
 for(let i=0;i<text.length;i++){const ch=text[i],next=text[i+1];if(ch==='"'&&quoted&&next==='"'){cell+='"';i++}else if(ch==='"')quoted=!quoted;else if(ch===','&&!quoted){row.push(cell.trim());cell=''}else if((ch==='\n'||ch==='\r')&&!quoted){if(ch==='\r'&&next==='\n')i++;row.push(cell.trim());if(row.some(Boolean))rows.push(row);row=[];cell=''}else cell+=ch}
 row.push(cell.trim());if(row.some(Boolean))rows.push(row);if(rows.length<2)throw new Error('The CSV needs a header and at least one course.');
 const headers=rows[0].map(v=>v.toLowerCase().replace(/\s+/g,''));for(const name of ['course','days','start','end'])if(!headers.includes(name))throw new Error(`Missing required column: ${name}`);
 return rows.slice(1).map((values,index)=>{const get=name=>values[headers.indexOf(name)]||'',tokens=get('days').toLowerCase().split(/[\/|;+\s]+/).filter(Boolean),days=tokens.map(t=>DAY_MAP[t]);if(!days.length||days.some(d=>d===undefined))throw new Error(`Row ${index+2}: use days like Mon Wed or Tue/Thu.`);const start=normalizeTime(get('start')),end=normalizeTime(get('end'));if(!start||!end)throw new Error(`Row ${index+2}: times must look like 09:00 or 2:30 PM.`);if(!get('course'))throw new Error(`Row ${index+2}: course is empty.`);const raw=get('session').toLowerCase(),session=raw.includes('1')||raw.includes('first')?'first':raw.includes('2')||raw.includes('second')?'second':'full';return{course:get('course'),days:[...new Set(days)],start,end,location:get('location'),session,notes:get('notes')}})
}
function dateFromIso(iso){const[y,m,d]=iso.split('-').map(Number);return new Date(y,m-1,d,12)}
function isoFromDate(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function expandSchedule(){const cal=CALENDARS[termSelect.value];events=[];courses.forEach((course,courseIndex)=>{const[startIso,endIso]=cal.sessions[course.session]||cal.sessions.full,cursor=dateFromIso(startIso),end=dateFromIso(endIso);while(cursor<=end){const iso=isoFromDate(cursor),closed=cal.closures.some(([a,b])=>iso>=a&&iso<=b);if(!closed){const effective=cal.swaps[iso]??cursor.getDay();if(course.days.includes(effective))events.push({...course,date:iso,courseIndex,makeUpFor:cal.swaps[iso]?DAY_NAMES[effective]:''})}cursor.setDate(cursor.getDate()+1)}});events.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}
function sessionLabel(s){return s==='first'?'Session 1':s==='second'?'Session 2':'Full term'}
function escapeHtml(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){
 expandSchedule();const empty=document.querySelector('#empty-preview'),preview=document.querySelector('#schedule-preview');
 if(!courses.length){empty.hidden=false;preview.hidden=true;exportButton.disabled=true;return}empty.hidden=true;preview.hidden=false;exportButton.disabled=!events.length;
 const makeups=events.filter(e=>e.makeUpFor).length;document.querySelector('#summary-strip').innerHTML=`<div class="metric"><strong>${courses.length}</strong><span>courses</span></div><div class="metric"><strong>${events.length}</strong><span>class events</span></div><div class="metric"><strong>${makeups}</strong><span>make-up meetings</span></div>`;
 document.querySelector('#course-list').innerHTML=courses.map((c,i)=>{const count=events.filter(e=>e.courseIndex===i).length;return`<article class="course-row"><span class="course-color" style="background:${COLORS[i%COLORS.length]}"></span><div class="course-main"><strong>${escapeHtml(c.course)}</strong><span>${escapeHtml(c.notes||'Class meeting')}</span></div><div class="course-detail"><strong>${c.days.map(d=>DAY_NAMES[d]).join(' · ')}</strong><span>${c.start}–${c.end}</span></div><div class="course-detail"><strong>${escapeHtml(c.location||'No room')}</strong><span>${count} dates · ${sessionLabel(c.session)}</span></div><button class="remove-course" data-remove="${i}" aria-label="Remove ${escapeHtml(c.course)}">×</button></article>`}).join('');
 document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{courses.splice(Number(b.dataset.remove),1);render()}))
}
function escIcs(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function stamp(iso,time){return iso.replaceAll('-','')+'T'+time.replace(':','')+'00'}
function createIcs(){const alert=document.querySelector('#alerts').checked,lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DKU Class Calendar//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:DKU Classes','X-WR-TIMEZONE:Asia/Shanghai'];events.forEach((e,i)=>{const note=[e.notes,e.makeUpFor?`DKU make-up day: ${e.makeUpFor} schedule is in effect.`:'','Generated using the DKU 2026–2027 academic calendar.'].filter(Boolean).join('\n');lines.push('BEGIN:VEVENT',`UID:${e.date}-${e.start}-${i}@dku-class-calendar`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Asia/Shanghai:${stamp(e.date,e.start)}`,`DTEND;TZID=Asia/Shanghai:${stamp(e.date,e.end)}`,`SUMMARY:${escIcs(e.course)}`,`LOCATION:${escIcs(e.location)}`,`DESCRIPTION:${escIcs(note)}`);if(alert)lines.push('BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY',`DESCRIPTION:${escIcs(e.course)} starts in 10 minutes`,'END:VALARM');lines.push('END:VEVENT')});lines.push('END:VCALENDAR');return lines.join('\r\n')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function handleFile(file){try{courses=parseCsv(await file.text());render();say(`${courses.length} courses loaded.`);document.querySelector('#preview-title').textContent='Review before you export';document.querySelector('#schedule-preview').scrollIntoView({behavior:'smooth',block:'start'})}catch(err){courses=[];render();document.querySelector('#schedule-preview').hidden=false;document.querySelector('#empty-preview').hidden=true;document.querySelector('#course-list').innerHTML=`<div class="error-box"><strong>Could not read that file.</strong><br>${escapeHtml(err.message)}</div>`;say('Please check the CSV format.')}}
fileInput.addEventListener('change',()=>fileInput.files[0]&&handleFile(fileInput.files[0]));
['dragenter','dragover'].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0]));
termSelect.addEventListener('change',()=>{if(courses.length){render();say(`${CALENDARS[termSelect.value].label} rules applied.`)}});
document.querySelector('#load-sample').addEventListener('click',()=>{courses=SAMPLE.map(c=>({...c,days:[...c.days]}));render();document.querySelector('#preview-title').textContent='Review before you export';say('Sample schedule loaded.')});
document.querySelector('#download-template').addEventListener('click',()=>download('dku-schedule-template.csv','course,days,start,end,location,session,notes\nCOMPSCI 201,"Mon Wed",10:05,11:20,IB 2026,full,Data Structures & Algorithms\nECON 101,"Tue Thu",13:15,14:30,WDR 1001,full,Economic Principles\nCHINESE 201,"Mon Tue Thu",15:05,15:55,CC 305,first,Intermediate Chinese\n','text/csv;charset=utf-8'));
exportButton.addEventListener('click',()=>{download(`DKU-${CALENDARS[termSelect.value].label.replace(' ','-')}.ics`,createIcs(),'text/calendar;charset=utf-8');say(`${events.length} class events exported.`)});
function registerWebMcp(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const inputSchema={type:'object',properties:{term:{type:'string',enum:['fall-2026','spring-2027']},courses:{type:'array',minItems:1,items:{type:'object',properties:{course:{type:'string'},days:{type:'array',items:{type:'integer',minimum:0,maximum:6}},start:{type:'string'},end:{type:'string'},location:{type:'string'},session:{type:'string',enum:['full','first','second']},notes:{type:'string'}},required:['course','days','start','end'],additionalProperties:false}}},required:['term','courses'],additionalProperties:false};Promise.resolve(ctx.registerTool({name:'stage_dku_schedule',title:'Stage DKU schedule',description:'Load a DKU course schedule into the visible converter and apply official 2026–2027 calendar rules.',inputSchema,annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!CALENDARS[input?.term]||!Array.isArray(input?.courses)||!input.courses.length)throw new Error('A supported term and at least one course are required.');termSelect.value=input.term;courses=input.courses.map(c=>({...c,session:c.session||'full',location:c.location||'',notes:c.notes||''}));render();return{term:input.term,courseCount:courses.length,eventCount:events.length}}})).catch(()=>{})}
registerWebMcp();
