const CALENDARS={
 'fall-2026':{label:'Fall 2026',sessions:{full:['2026-08-24','2026-12-10'],first:['2026-08-24','2026-10-15'],second:['2026-10-26','2026-12-10']},closures:[['2026-09-25','2026-09-27'],['2026-10-01','2026-10-11']],swaps:{'2026-09-18':4}},
 'spring-2027':{label:'Spring 2027',sessions:{full:['2027-01-11','2027-05-07'],first:['2027-01-11','2027-03-04'],second:['2027-03-22','2027-05-07']},closures:[['2027-02-05','2027-02-14'],['2027-04-05','2027-04-05'],['2027-05-01','2027-05-03']],swaps:{'2027-04-06':1,'2027-04-07':2,'2027-04-08':3,'2027-04-09':4,'2027-05-04':1,'2027-05-05':2,'2027-05-06':3,'2027-05-07':4}}
};
const DAY_NAMES=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'], COLORS=['#78c8ff','#ff82b7','#a8e85a','#ffd94d','#9d83ff'];
const ICS_DAY_MAP={SU:0,MO:1,TU:2,WE:3,TH:4,FR:5,SA:6};
const SAMPLE=[
 {course:'COMPSCI 201',days:[1,3],start:'10:05',end:'11:20',location:'IB 2026',session:'full',notes:'Data Structures & Algorithms'},
 {course:'ECON 101',days:[2,4],start:'13:15',end:'14:30',location:'WDR 1001',session:'full',notes:'Economic Principles'},
 {course:'CHINESE 201',days:[1,2,4],start:'15:05',end:'15:55',location:'CC 305',session:'first',notes:'Intermediate Chinese'}
];
let courses=[],events=[],extraEvents=[];
const fileInput=document.querySelector('#schedule-file'),dropzone=document.querySelector('.dropzone'),toast=document.querySelector('#toast'),exportButton=document.querySelector('#export-button'),termSelect=document.querySelector('#term-select');

function say(message){toast.textContent=message;toast.classList.add('show');clearTimeout(say.timer);say.timer=setTimeout(()=>toast.classList.remove('show'),2400)}
function normalizeTime(value){const m=value.trim().match(/^(\d{1,2}):(\d{2})\s*(AM|PM)?$/i);if(!m)return'';let h=Number(m[1]);const min=Number(m[2]),ap=m[3]?.toUpperCase();if(min>59||h>(ap?12:23))return'';if(ap==='PM'&&h<12)h+=12;if(ap==='AM'&&h===12)h=0;return`${String(h).padStart(2,'0')}:${String(min).padStart(2,'0')}`}
function unfoldIcs(text){return text.replace(/\r?\n[ \t]/g,'').split(/\r?\n/)}
function unescIcs(v=''){return v.replace(/\\[nN]/g,'\n').replace(/\\,/g,',').replace(/\\;/g,';').replace(/\\\\/g,'\\')}
function readIcsDate(raw){const value=raw.split(':').pop().trim(),m=value.match(/^(\d{4})(\d{2})(\d{2})(?:T(\d{2})(\d{2})(\d{2})?)?(Z)?$/);if(!m)return null;let[,y,mo,d,h='00',mi='00',s='00',z]=m;if(z){const date=new Date(Date.UTC(+y,+mo-1,+d,+h,+mi,+s)),parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(date),get=t=>parts.find(p=>p.type===t)?.value;return{date:`${get('year')}-${get('month')}-${get('day')}`,time:`${get('hour')}:${get('minute')}`}}return{date:`${y}-${mo}-${d}`,time:`${h}:${mi}`}}
function property(block,name){const line=block.find(v=>v.toUpperCase().startsWith(name+':')||v.toUpperCase().startsWith(name+';'));return line?line.slice(line.indexOf(':')+1):''}
function inferSession(startDate,untilDate){const cal=CALENDARS[termSelect.value];if(untilDate&&untilDate<=cal.sessions.first[1])return'first';if(startDate>=cal.sessions.second[0])return'second';return'full'}
function parseIcs(text){
 const lines=unfoldIcs(text),blocks=[];let current=null;for(const line of lines){if(line.toUpperCase()==='BEGIN:VEVENT')current=[];else if(line.toUpperCase()==='END:VEVENT'){if(current)blocks.push(current);current=null}else if(current)current.push(line)}
 if(!blocks.length)throw new Error('No calendar events were found in that .ics file.');
 const parsed=blocks.map((block,index)=>{const summary=unescIcs(property(block,'SUMMARY')).trim(),startRaw=block.find(v=>/^DTSTART[;:]/i.test(v)),endRaw=block.find(v=>/^DTEND[;:]/i.test(v)),start=startRaw&&readIcsDate(startRaw),end=endRaw&&readIcsDate(endRaw);if(!summary||!start||!end||start.time==='00:00'&&end.time==='00:00')return null;const rrule=property(block,'RRULE'),rule=Object.fromEntries(rrule.split(';').filter(Boolean).map(v=>{const at=v.indexOf('=');return at<0?[v,'']:[v.slice(0,at).toUpperCase(),v.slice(at+1)]})),days=(rule.BYDAY?rule.BYDAY.split(',').map(v=>ICS_DAY_MAP[v.slice(-2).toUpperCase()]):[dateFromIso(start.date).getDay()]).filter(v=>v!==undefined),until=rule.UNTIL?readIcsDate('X:'+rule.UNTIL)?.date:start.date;return{course:summary,days:[...new Set(days)],start:start.time,end:end.time,location:unescIcs(property(block,'LOCATION')),session:inferSession(start.date,until),notes:unescIcs(property(block,'DESCRIPTION')),sourceStart:start.date,sourceUntil:until,index}}).filter(Boolean);
 if(!parsed.length)throw new Error('No timed class events were found. All-day events are skipped.');
 const grouped=new Map();for(const item of parsed){const key=[item.course,item.start,item.end,item.location,item.session].join('|');if(!grouped.has(key))grouped.set(key,item);else grouped.get(key).days=[...new Set([...grouped.get(key).days,...item.days])]}
 return [...grouped.values()].map(({index,...course})=>course);
}
function dateFromIso(iso){const[y,m,d]=iso.split('-').map(Number);return new Date(y,m-1,d,12)}
function isoFromDate(d){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function expandSchedule(){const cal=CALENDARS[termSelect.value];events=[];courses.forEach((course,courseIndex)=>{const fallback=cal.sessions[course.session]||cal.sessions.full,startIso=course.sourceStart||fallback[0],endIso=course.sourceUntil||fallback[1],cursor=dateFromIso(startIso),end=dateFromIso(endIso);while(cursor<=end){const iso=isoFromDate(cursor),closed=cal.closures.some(([a,b])=>iso>=a&&iso<=b);if(!closed){const effective=cal.swaps[iso]??cursor.getDay();if(course.days.includes(effective))events.push({...course,date:iso,courseIndex,makeUpFor:cal.swaps[iso]?DAY_NAMES[effective]:''})}cursor.setDate(cursor.getDate()+1)}});events.sort((a,b)=>(a.date+a.start).localeCompare(b.date+b.start))}
function sessionLabel(s){return s==='first'?'Session 1':s==='second'?'Session 2':'Full term'}
function escapeHtml(v){return String(v).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function parseExtraEvent(value){
 const text=value.trim();if(!text)throw new Error('Say or type an event first.');
 let title='',date='',start='',end='',location='',notes='';
 const natural=text.match(/^(.+?)\s+on\s+(\d{4}-\d{2}-\d{2})\s+from\s+([^\s]+(?:\s*[AP]M)?)\s+to\s+([^\s]+(?:\s*[AP]M)?)(?:\s+at\s+(.+))?$/i);
 if(natural){[,title,date,start,end,location='']=natural}
 else{const parts=text.split('|').map(v=>v.trim());if(parts.length<4)throw new Error('Use “Title on YYYY-MM-DD from HH:MM to HH:MM at Location”.');[title,date,start,end,location='',notes='']=parts}
 if(!/^\d{4}-\d{2}-\d{2}$/.test(date)||isoFromDate(dateFromIso(date))!==date)throw new Error('Use a valid date like 2026-09-18.');
 start=normalizeTime(start);end=normalizeTime(end);if(!start||!end||end<=start)throw new Error('Use valid times, with the end after the start.');
 if(!title)throw new Error('Add an event title.');return{title,date,start,end,location,notes};
}
function renderExtraEvents(){const list=document.querySelector('#extra-event-list');list.innerHTML=extraEvents.map((e,i)=>`<article class="extra-event-row"><span class="extra-event-dot" aria-hidden="true"></span><div><strong>${escapeHtml(e.title)}</strong><span>${escapeHtml(e.date)} · ${e.start}–${e.end}${e.location?` · ${escapeHtml(e.location)}`:''}</span></div><button class="remove-course" data-remove-extra="${i}" aria-label="Remove ${escapeHtml(e.title)}">×</button></article>`).join('');document.querySelectorAll('[data-remove-extra]').forEach(b=>b.addEventListener('click',()=>{extraEvents.splice(Number(b.dataset.removeExtra),1);render()}))}
function render(){
 expandSchedule();const empty=document.querySelector('#empty-preview'),preview=document.querySelector('#schedule-preview');
 renderExtraEvents();if(!courses.length&&!extraEvents.length){empty.hidden=false;preview.hidden=true;exportButton.disabled=true;return}empty.hidden=true;preview.hidden=false;exportButton.disabled=!(events.length||extraEvents.length);
 const makeups=events.filter(e=>e.makeUpFor).length;document.querySelector('#summary-strip').innerHTML=`<div class="metric"><strong>${courses.length}</strong><span>courses</span></div><div class="metric"><strong>${events.length}</strong><span>class events</span></div><div class="metric"><strong>${extraEvents.length}</strong><span>extra events</span></div><div class="metric"><strong>${makeups}</strong><span>make-up meetings</span></div>`;
 document.querySelector('#course-list').innerHTML=courses.map((c,i)=>{const dates=events.filter(e=>e.courseIndex===i).map(e=>e.date),count=dates.length,range=count?`${dates[0]} → ${dates.at(-1)}`:sessionLabel(c.session);return`<article class="course-row"><span class="course-color" style="background:${COLORS[i%COLORS.length]}"></span><div class="course-main"><strong>${escapeHtml(c.course)}</strong><span>${escapeHtml(c.notes||'Class meeting')}</span></div><div class="course-detail"><strong>${c.days.map(d=>DAY_NAMES[d]).join(' · ')}</strong><span>${c.start}–${c.end}</span></div><div class="course-detail"><strong>${escapeHtml(c.location||'No room')}</strong><span>${count} dates · ${range}</span></div><button class="remove-course" data-remove="${i}" aria-label="Remove ${escapeHtml(c.course)}">×</button></article>`}).join('');
 document.querySelectorAll('[data-remove]').forEach(b=>b.addEventListener('click',()=>{courses.splice(Number(b.dataset.remove),1);render()}))
}
function escIcs(v){return String(v||'').replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;')}
function stamp(iso,time){return iso.replaceAll('-','')+'T'+time.replace(':','')+'00'}
function addIcsEvent(lines,event,index,alert){lines.push('BEGIN:VEVENT',`UID:${event.date}-${event.start}-${index}@dku-class-calendar`,`DTSTAMP:${new Date().toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'')}`,`DTSTART;TZID=Asia/Shanghai:${stamp(event.date,event.start)}`,`DTEND;TZID=Asia/Shanghai:${stamp(event.date,event.end)}`,`SUMMARY:${escIcs(event.title)}`,`LOCATION:${escIcs(event.location)}`,`DESCRIPTION:${escIcs(event.notes)}`);if(alert)lines.push('BEGIN:VALARM','TRIGGER:-PT10M','ACTION:DISPLAY',`DESCRIPTION:${escIcs(event.title)} starts in 10 minutes`,'END:VALARM');lines.push('END:VEVENT')}
function createIcs(){const alert=document.querySelector('#alerts').checked,lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DKU Class Calendar//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:DKU Classes + Extras','X-WR-TIMEZONE:Asia/Shanghai'];events.forEach((e,i)=>addIcsEvent(lines,{...e,title:e.course,notes:[e.notes,e.makeUpFor?`DKU make-up day: ${e.makeUpFor} schedule is in effect.`:'','Generated using the DKU 2026–2027 academic calendar.'].filter(Boolean).join('\n')},`class-${i}`,alert));extraEvents.forEach((e,i)=>addIcsEvent(lines,e,`extra-${i}`,alert));lines.push('END:VCALENDAR');return lines.join('\r\n')}
function download(name,content,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
async function handleFile(file){try{courses=parseIcs(await file.text());render();say(`${courses.length} course patterns loaded.`);document.querySelector('#preview-title').textContent='Review before you export';document.querySelector('#schedule-preview').scrollIntoView({behavior:'smooth',block:'start'})}catch(err){courses=[];render();document.querySelector('#schedule-preview').hidden=false;document.querySelector('#empty-preview').hidden=true;document.querySelector('#course-list').innerHTML=`<div class="error-box"><strong>Could not read that .ics file.</strong><br>${escapeHtml(err.message)}</div>`;say('Please check the .ics file.')}}
fileInput.addEventListener('change',()=>fileInput.files[0]&&handleFile(fileInput.files[0]));
['dragenter','dragover'].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.add('drag')}));['dragleave','drop'].forEach(n=>dropzone.addEventListener(n,e=>{e.preventDefault();dropzone.classList.remove('drag')}));dropzone.addEventListener('drop',e=>e.dataTransfer.files[0]&&handleFile(e.dataTransfer.files[0]));
termSelect.addEventListener('change',()=>{if(courses.length){render();say(`${CALENDARS[termSelect.value].label} rules applied.`)}});
document.querySelector('#load-sample').addEventListener('click',()=>{courses=SAMPLE.map(c=>({...c,days:[...c.days]}));render();document.querySelector('#preview-title').textContent='Review before you export';say('Sample schedule loaded.')});
exportButton.addEventListener('click',()=>{download(`DKU-${CALENDARS[termSelect.value].label.replace(' ','-')}-corrected.ics`,createIcs(),'text/calendar;charset=utf-8');say(`${events.length+extraEvents.length} events exported.`);const guide=document.querySelector('#import-guide');guide.hidden=false;guide.scrollIntoView({behavior:'smooth',block:'start'})});
document.querySelector('#add-extra-event').addEventListener('click',()=>{const input=document.querySelector('#extra-event-input');try{extraEvents.push(parseExtraEvent(input.value));input.value='';render();document.querySelector('#preview-title').textContent='Review before you export';say('Extra event added.')}catch(err){say(err.message)}});
const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition,voiceButton=document.querySelector('#voice-input'),voiceStatus=document.querySelector('#voice-status');
if(SpeechRecognition){const recognition=new SpeechRecognition();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=1;voiceButton.addEventListener('click',()=>{voiceButton.classList.add('listening');voiceButton.innerHTML='<span aria-hidden="true">●</span> Listening…';voiceStatus.textContent='Speak your event in English.';recognition.start()});recognition.addEventListener('result',e=>{document.querySelector('#extra-event-input').value=e.results[0][0].transcript;voiceStatus.textContent='Voice captured. Check it, then add the event.'});recognition.addEventListener('end',()=>{voiceButton.classList.remove('listening');voiceButton.innerHTML='<span aria-hidden="true">●</span> Speak'});recognition.addEventListener('error',e=>{voiceStatus.textContent=e.error==='not-allowed'?'Microphone access was not allowed. You can still type.':'I could not hear that. Please try again.'})}else{voiceButton.disabled=true;voiceStatus.textContent='Voice input is not supported here. You can still type.'}
function registerWebMcp(){const ctx=document.modelContext;if(!ctx?.registerTool)return;const inputSchema={type:'object',properties:{term:{type:'string',enum:['fall-2026','spring-2027']},courses:{type:'array',minItems:1,items:{type:'object',properties:{course:{type:'string'},days:{type:'array',items:{type:'integer',minimum:0,maximum:6}},start:{type:'string'},end:{type:'string'},location:{type:'string'},session:{type:'string',enum:['full','first','second']},notes:{type:'string'}},required:['course','days','start','end'],additionalProperties:false}}},required:['term','courses'],additionalProperties:false};Promise.resolve(ctx.registerTool({name:'stage_dku_schedule',title:'Stage DKU schedule',description:'Load a DKU course schedule into the visible converter and apply official 2026–2027 calendar rules.',inputSchema,annotations:{readOnlyHint:false,untrustedContentHint:true},execute(input){if(!CALENDARS[input?.term]||!Array.isArray(input?.courses)||!input.courses.length)throw new Error('A supported term and at least one course are required.');termSelect.value=input.term;courses=input.courses.map(c=>({...c,session:c.session||'full',location:c.location||'',notes:c.notes||''}));render();return{term:input.term,courseCount:courses.length,eventCount:events.length}}})).catch(()=>{})}
registerWebMcp();
